apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserve
  labels:
    app: reserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reserve
  template:
    metadata:
      labels:
        app: reserve
    spec:
      containers:
        - name: reserve
          image: uuser08skccacr.azurecr.io/reserve:v1
          ports:
            - containerPort: 8080         
          #readinessProbe:
          #  tcpSocket:
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          # failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5