server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://localhost:8081
          predicates:
            - Path=/reserves/** 
        - id: customercenter
          uri: http://localhost:8082
          predicates:
            - Path= /mypages/**
        - id: pay
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: cinema
          uri: http://localhost:8084
          predicates:
            - Path=/cinemas/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/reserves/** 
        - id: customercenter
          uri: http://customercenter:8080
          predicates:
            - Path= /mypages/**
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/** 
        - id: cinema
          uri: http://cinema:8080
          predicates:
            - Path=/cinemas/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080